In [28]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, accuracy_score

In [42]:
dataset = pd.read_csv('data/twitter_dataset.csv', encoding = 'latin-1')
dataset.head()

,name_wt,statuses_count,followers_count,friends_count,favourites_count,listed_count,label
0,0.857143,1211,24,63,6,6,0
1,0.250000,313,101,173,48,0,0
2,0.411765,247,51,382,50,4,0
3,0.611111,41,3,36,5,0,0
4,0.600000,12341,770,1417,0,8,1

In [43]:
features=[]
for attributes in dataset.columns:
    if attributes != 'label':
        features.append(attributes)
features

['name_wt',
 'statuses_count',
 'followers_count',
 'friends_count',
 'favourites_count',
 'listed_count']

In [44]:
X = np.array(dataset.drop(['label'], 1).astype(float))
# scaler = MinMaxScaler()
# X_scaled = scaler.fit_transform(X)

In [45]:
y = np.array(dataset['label'])

In [46]:
kmeans = KMeans(n_clusters=2,max_iter=1000,verbose=1) 
# kmeans.fit(X_scaled)
kmeans.fit(X)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 6438003986629.357
start iteration
done sorting
end inner loop
Iteration 1, inertia 6438003986629.357
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 12046624405650.53
start iteration
done sorting
end inner loop
Iteration 1, inertia 12032907824424.807
start iteration
done sorting
end inner loop
Iteration 2, inertia 12026519011534.229
start iteration
done sorting
end inner loop
Iteration 3, inertia 12023117283179.197
start iteration
done sorting
end inner loop
Iteration 4, inertia 12021671076115.14
start iteration
done sorting
end inner loop
Iteration 5, inertia 12019212631487.418
start iteration
done sorting
end inner loop
Iteration 6, inertia 12017075275687.088
start iteration
done sorting
end inner loop
Iteration 7, inertia 12015986556505.355
start iteration
done sorting
end inner loop
Iteration 8, inertia 12015452174734.012
start iteration
done sorting
end inner loop
Iteration 9, inertia 12015394383935.197
start iteration
done sorting
end inner loop
Iteration 10, inertia 12015394383935.197
center shift 0.000000e+00 within tolerance 3.461756e+04
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 5436957891125.498
start iteration
done sorting
end inner loop
Iteration 1, inertia 5436957891125.498
center shift 0.000000e+00 within tolerance 3.461756e+04

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=1000,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [47]:
correct = 0
# for i in range(len(X)):
#     predict_me = np.array(X[i].astype(float))
#     predict_me = predict_me.reshape(-1, len(predict_me))
#     prediction = kmeans.predict(predict_me)
#     print(prediction)
#     if prediction[0] == y[i]:
# #         print(i)
#         correct += 1
predictions=kmeans.predict(X)
# print(predictions)
# print(correct/len(X))
print (predictions)
for i in range(len(predictions)):
    if predictions[i]==1:
        print (i)

[0 0 0 ... 0 0 0]
27

In [35]:
y[27]

1

In [135]:
predict_me = np.array(X[6922].astype(float))
predict_me = predict_me.reshape(-1, len(predict_me))
predict_me.shape

(1, 6)

In [79]:
kmeans.predict(predict_me)[0]

0

In [29]:
dataset

,name_wt,statuses_count,followers_count,friends_count,favourites_count,listed_count,label
0,0.857143,1211,24,63,6,6,0
1,0.250000,313,101,173,48,0,0
2,0.411765,247,51,382,50,4,0
3,0.611111,41,3,36,5,0,0
4,0.600000,12341,770,1417,0,8,1
5,0.625000,4,134,1731,0,1,1
6,0.363636,17229,271,418,1965,7,0
7,0.909091,1816,139,320,1529,0,0
8,0.333333,14210,320,193,13278,1,0
9,0.928571,41690,3174,772,607,57,0
10,0.923077,3278,204,459,396,11,0
11,0.133333,253,3491,3705,0,3,1
12,0.933333,62,6,35,0,0,1
13,0.923077,85,592,1695,0,1,1
14,0.923077,123,0,0,0,0,1
15,0.142857,33917,2139,1279,6111,21,0
16,0.416667,764,79,92,0,3,1
17,0.933333,43,5,34,0,0,1
18,0.153846,45599,23,9,2,11,1
19,0.923077,851,374,322,25,4,1
20,0.937500,43,5,40,0,0,1
21,0.333333,400,13,68,54,0,0
22,0.333333,12565,2565,226,17990,7,0
23,0.666667,4789,439,287,7911,1,0
24,0.923077,38,5,36,0,0,1
25,0.750000,171,10,60,0,0,1
26,1.000000,15890,973,1994,566,12,0
27,0.666667,28897,2991573,211890,10,24348,1
28,0.818182,108,612,503,0,53,1
29,0.875000,42,6,42,0,0,1
...,...,...,...,...,...,...,...
6915,0.666667,5768,567,539,1057,2,0
6916,0.933333,86,11,37,0,0,1
6917,0.642857,4,51,247,0,0,1
6918,1.000000,279,60,119,68,0,0
6919,0.500000,32685,566,358,10413,2,0
6920,0.700000,12400,20973,59,0,1,1
6921,1.000000,2,127,684,0,0,1
6922,0.705882,112,1,0,0,0,1
6923,0.444444,99,303,271,0,20,1
6924,1.000000,258,4466,4759,0,3,1
6925,0.100000,1290,1782,164,1057,16,0
6926,0.833333,61,642,538,0,12,1
6927,0.100000,526,224,303,5333,2,0
6928,0.933333,46,4,34,0,0,1
6929,0.937500,68,2,34,0,0,1
6930,0.235294,10577,2158,939,28304,16,0
6931,0.631579,22,279,278,0,3,1
6932,0.250000,20997,498,109,12105,5,0
6933,0.937500,65,3,43,0,0,1
6934,1.000000,1,197,521,0,1,1
6935,0.928571,58,1,32,0,0,1
6936,1.000000,14676,282,487,2028,4,0
6937,0.923077,53,3,38,0,0,1
6938,0.500000,5348,361,195,3392,3,0
6939,0.928571,36166,828,289,474,57,0
6940,0.444444,14187,358,967,280,8,0
6941,0.928571,73,7,41,0,0,1
6942,0.500000,274989,9815,2190,40114,38,0
6943,1.000000,169631,2338,973,230,79,0
6944,1.000000,1,130,773,0,0,1

In [105]:
X_scaled

array([[8.57142857e-01, 3.03087184e-03, 8.02253530e-06, 2.97324083e-04,
        1.91110800e-05, 2.46426811e-04],
       [2.50000000e-01, 7.83371501e-04, 3.37615027e-05, 8.16461371e-04,
        1.52888640e-04, 0.00000000e+00],
       [4.11764706e-01, 6.18187734e-04, 1.70478875e-05, 1.80282222e-03,
        1.59259000e-04, 1.64284541e-04],
       ...,
       [5.00000000e-01, 6.88238165e-01, 3.28088267e-03, 1.03355515e-02,
        1.27770310e-01, 1.56070314e-03],
       [1.00000000e+00, 4.24549812e-01, 7.81528647e-04, 4.59200529e-03,
        7.32591399e-04, 3.24461968e-03],
       [1.00000000e+00, 2.50278435e-06, 4.34553996e-05, 3.64811931e-03,
        0.00000000e+00, 0.00000000e+00]])